apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-certificate
spec:
  dnsNames:
    - 'native-ha-qm-ibm-mq-qm-mq.apps.6639dc375291bf001ec9fde7.cloud.techzone.ibm.com'
    - 'native-ha-qm-ibm-mq-web-mq.apps.6639dc375291bf001ec9fde7.cloud.techzone.ibm.com'