kind: WebSphereLibertyApplication
apiVersion: liberty.websphere.ibm.com/v1
metadata:
  name: websphereliberty-app-sample
spec:
  envFrom:
   - secretRef:
      # Should be manually created in the cluster (or via vault). Key should be MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_SASL_JAAS_CONFIG
      # and value org.apache.kafka.common.security.scram.ScramLoginModule required username="<username>" password="<password>";
      name: liberty-config
  networkPolicy:
    disable: true
  service:
    type: ClusterIP
    port: 9443
    portName: https
    targetPort: 9443
    ports:
      - port: 2809
        name: iiop
  #serviceability:
  #  size: 5Gi
  #  storageClassName: ocs-storagecluster-cephfs
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: TBASIC
  applicationImage: >-
    ghcr.io/nordic-mvp-gitops-repos/liberty-sampleapp:latest
  expose: true
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  manageTLS: true
  replicas: 1
  pullPolicy: Always
  serviceAccount:
    mountToken: true
#  volumeMounts:
#    - name: config-dropins
#      mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/jvm.options
#      subPath: jvm.options
#  volumes:
#    - name: config-dropins
#      configMap:
#        name: config-dropins
