apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eventprocessing-ui-certificate
spec:
  dnsNames:
    - ibm-event-processing-ibm-ep-rt-eventprocessing.apps.6639dc375291bf001ec9fde7.cloud.techzone.ibm.com